Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-09, with the labels that each got.

#161 Read mode date value era and calendar
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
Labels: enhancement

#165 release(prerelease): 1.0.0-rc.4
  CHANGELOG.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: chore

#166 Update peer-dep for dsp-js lib
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: dependencies

#167 Prerelease: 1.0.0-rc.5
  CHANGELOG.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: chore

#168 Message component timer
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#169 Search Panel: Advanced Search Not Displayed
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.scss
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
Labels: bug, styling

#154 Hide system ontologies
  e2e/src/app.e2e-spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.html
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
Labels: refactor

#170 Rephrase "This source belongs to project" in the resource viewer
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html
Labels: refactor

#172 Show label for URI Value (if set)
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
Labels: enhancement

#174 Confirmation Dialog Message Subcomponent
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.spec.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  src/app/action-playground/action-playground.component.ts
Labels: refactor

#171 FIX: Delete Value UI Bug
  e2e/src/app.e2e-spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: bug

#173 Viewer: Use span Elements instead of div and p in Read Mode
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss
Labels: help wanted, question, styling

#175 Fix compareObjectTypeWithValueType Method
  projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
Labels: chore

#176 Prerelease: 1.0.0-rc.6
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: release

#177 fix: Update peer dependencies for js-lib
  projects/dsp-ui/package.json
Labels: dependencies

#178 Prerelease 1.0.0-rc.7
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: release

#180 Message Component Css
  projects/dsp-ui/src/lib/action/components/message/message.component.scss
Labels: styling

#179 docs: Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#134 Add CKeditor
  package-lock.json
  package.json
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/ng-package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/ckeditor/ckeditor-playground/ckeditor-playground.component.html
  src/app/ckeditor/ckeditor-playground/ckeditor-playground.component.scss
  src/app/ckeditor/ckeditor-playground/ckeditor-playground.component.spec.ts
  src/app/ckeditor/ckeditor-playground/ckeditor-playground.component.ts
  src/config/config.dev.json
  src/config/config.prod.json
Labels: enhancement

#181 test: Update api version
  Makefile
  README.md
Labels: dependencies, documentation, testing

#182 FIX: Boolean add button
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
Labels: bug

#185 Date & Interval Components: Remove Parent Input Placeholder
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
Labels: styling

#183 DSP-619 Update release process
  .github/release-drafter.yml
  .github/workflows/main.yml
  .grenrc
  Makefile
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: chore

#186 DSP-672 Update dependency
  CHANGELOG.md
  Makefile
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: dependencies

#157 System Prop Info
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
Labels: enhancement

#187 Hide Geometry Property
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: refactor

#189 DSP-693 Sort button style
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.html
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.scss
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
  src/app/action-playground/action-playground.component.html
Labels: enhancement, styling

#192 Default Boolean Value
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
Labels: enhancement, refactor

#194 DSP-436 Fix workflow issue
  .github/workflows/main.yml
  Makefile
Labels: bug

#195 DSP-701 Add template for PRs
  .github/pull_request_template.md
Labels: chore

#193 Geoname Value Styling
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
Labels: refactor, styling

#197 DSP-708 Refactor CI workflow script
  .github/workflows/main.yml
Labels: chore

#184 Date Value Component Polish
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
Labels: styling
