Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-11, with the labels that each got.

#214 DSP-759 Check if a Given Date Can Be Edited
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: breaking, enhancement

#217 Create user service
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/user.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/user.service.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts
  src/app/viewer-playground/viewer-playground.component.spec.ts
Labels: bug, enhancement

#219 Update dependencies
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  vars.mk
Labels: dependencies

#212 DSP-788 Fix compatibility issues with CKEditor version 4
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
Labels: bug, user requirement

#225 Explain Demo App (Playground)
  README.md
Labels: documentation

#220 Propagate Click Event to Res Viewer Comp.
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/viewer-playground/viewer-playground.component.html
  src/app/viewer-playground/viewer-playground.component.ts
Labels: enhancement

#226 DSP-924 Never Import from index.ts Internally
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.spec.ts
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.spec.ts
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/select-property.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.ts
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.spec.ts
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: bug

#222 DSP-768 Styling issue in resource (properties) viewer
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss
  src/app/viewer-playground/viewer-playground.component.ts
Labels: bug, styling

#221 DSP-885 Fix default gravsearch query
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.ts
Labels: bug

#218 DSP-904 upload form for representations
  projects/dsp-ui/src/lib/action/services/notification.service.ts
  projects/dsp-ui/src/lib/viewer/directives/drag-drop.directive.spec.ts
  projects/dsp-ui/src/lib/viewer/directives/drag-drop.directive.ts
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.html
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.scss
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.spec.ts
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.ts
  projects/dsp-ui/src/lib/viewer/services/upload-file.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/upload-file.service.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/upload-playground/upload-playground.component.html
  src/app/upload-playground/upload-playground.component.scss
  src/app/upload-playground/upload-playground.component.spec.ts
  src/app/upload-playground/upload-playground.component.ts
  src/config/config.dev.json
  src/config/config.prod.json
Labels: enhancement

#227 DSP-1028 Activate still-image in resource viewer
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.scss
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/viewer-playground/viewer-playground.component.ts
Labels: enhancement

#229 DSP-1075 Bug in notification service
  projects/dsp-ui/src/lib/action/services/notification.service.ts
Labels: bug

#228 Update standoff link value
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/modify/modify.component.html
  src/app/modify/modify.component.ts
Labels: breaking, enhancement

#232 Add missing decorator to ValueOperationEventService
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
Labels: enhancement

#234 DSP-1097 - Bump JS-Lib Version and Fix Breaking Changes
  package-lock.json
  package.json
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  src/app/still-image/still-image-playground.component.spec.ts
  src/app/viewer-playground/viewer-playground.component.spec.ts
Labels: chore

#235 Update to v13.0.0-rc.23
  vars.mk
Labels: chore

#233 Determine from ontology if a property is read-only
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
Labels: breaking, enhancement

#236 Update DSP dependencies
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  vars.mk
Labels: dependencies

#224 CKEditor Backward Compatibility
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
Labels: bug, user requirement

#213 DSP-869 add select project component
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/select-project/select-project.component.html
  projects/dsp-ui/src/lib/action/components/select-project/select-project.component.scss
  projects/dsp-ui/src/lib/action/components/select-project/select-project.component.spec.ts
  projects/dsp-ui/src/lib/action/components/select-project/select-project.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.spec.ts
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#230 DSP-945-update resource viewer
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement
