Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-10, with the labels that each got.

#200 DSP-777 Show message on all server errors in login component
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
Labels: enhancement

#191 Color Value Polish
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.html
  projects/dsp-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts
Labels: styling

#198 Value Deletion Comment
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
Labels: enhancement

#199 Integrate Ckeditor into Property View
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  src/config/config.dev.json
  src/config/config.prod.json
Labels: breaking, enhancement

#205 DSP-674 Bug fix in search panel
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
Labels: bug

#202 Handle links in XML text values
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/src/lib/viewer/directives/text-value-html-link.directive.spec.ts
  projects/dsp-ui/src/lib/viewer/directives/text-value-html-link.directive.ts
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
Labels: enhancement

#201 DSP-779 Display error messages directly and not only in console
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.html
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.html
  projects/dsp-ui/src/lib/action/components/message/message.component.scss
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.html
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/search.module.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/action-playground/action-playground.component.html
Labels: enhancement

#207 DSP-806 - Add the attribute 'rel' to uri and geoname value component template
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
Labels: enhancement

#209 Update DSP-JS-Lib
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: dependencies

#208 DSP-762 Error handling and notification service
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.html
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.spec.ts
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/action/services/notification.service.spec.ts
  projects/dsp-ui/src/lib/action/services/notification.service.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement

#206 DSP-522 Refactor search panel style
  projects/dsp-ui/src/assets/style/_responsive.scss
  projects/dsp-ui/src/assets/style/_search.scss
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.html
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.scss
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.scss
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  src/app/app.module.ts
  src/app/search-playground/search-playground.component.html
  src/app/search-playground/search-playground.component.scss
  src/app/search-playground/search-playground.component.spec.ts
  src/app/search-playground/search-playground.component.ts
Labels: styling

#215 Update dsp-js-lib
  Makefile
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.spec.ts
  projects/dsp-ui/src/lib/core/session.service.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-ontology/select-ontology.component.spec.ts
Labels: dependencies

#210 DSP-881 - Value Component Base Class Changes
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
  projects/dsp-ui/src/lib/viewer/values/base-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
Labels: chore

#216 DSP-920 Renaming default github branch to "main"
  .github/pull_request_template.md
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  projects/dsp-ui/README.md
Labels: chore
