Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-04, with the labels that each got.

#56 Simulate productive circumstances locally
  .github/workflows/nodejs.yml
  README.md
  angular.json
  package.json
  projects/knora-ui/README.md
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts
  src/config/config.prod.json
  src/environments/environment.prod.ts
Labels: enhancement

#43 Value Component CSS and other styling
  package-lock.json
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/knora-ui/src/lib/viewer/values/base-value.component.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.scss
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.scss
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.scss
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.scss
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.scss
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.scss
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.scss
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.scss
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/index.html
Labels: enhancement, styling

#42 Prototyping property viewer with the value components
  projects/knora-ui/src/lib/viewer/index.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.scss
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.scss
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
Labels: enhancement

#58 Clean up prop label
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.html
Labels: bug, styling

#57 Geoname mat-icon suffix
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
Labels: enhancement, styling

#59 Add missing config files
  .editorconfig
  README.md
  update_docs.sh
Labels: chore

#66 BUG: User can no longer save an edited value
  package-lock.json
Labels: bug

#63 Upgrade to Angular 9
  .github/workflows/nodejs.yml
  angular.json
  package-lock.json
  package.json
  projects/knora-ui/package.json
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/knora-ui/src/lib/viewer/values/base-value.component.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/knora-ui/src/lib/viewer/values/date-value/calendar-header/calendar-header.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/calendar-header/calendar-header.component.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/knora-ui/src/lib/viewer/values/jdn-datepicker-directive/jdndatepicker.directive.spec.ts
  projects/knora-ui/src/lib/viewer/values/jdn-datepicker-directive/jdndatepicker.directive.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/knora-ui/src/lib/viewer/values/list-value/subList-value/sublist-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/knora-ui/tsconfig.lib.json
  projects/knora-ui/tsconfig.lib.prod.json
  src/app/modify/modify.component.spec.ts
  src/app/read/read.component.spec.ts
  tsconfig.app.json
  yalc.lock
Labels: breaking, chore, enhancement

#64 Add Exports
  projects/knora-ui/src/lib/viewer/index.ts
  projects/knora-ui/src/lib/viewer/values/index.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
Labels: chore

#69 Create Value Comparison Method
  projects/knora-ui/src/lib/viewer/values/base-value.component.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
Labels: enhancement, refactor

#68 Rename knora-ui package to @knora/ui
  README.md
  angular.json
  package-lock.json
  package.json
  projects/knora-ui/README.md
  projects/knora-ui/ng-package.json
  projects/knora-ui/package.json
  src/app/app-init.service.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/modify/modify.component.spec.ts
  src/app/modify/modify.component.ts
  src/app/read/read.component.spec.ts
  src/app/read/read.component.ts
  tsconfig.json
Labels: breaking
