Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-07, with the labels that each got.

#116 Add ArkUrl copy to clipboard in resource-view
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement

#120 Fix tests to remove error messages in the console
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
Labels: warning

#118 AppInitService: Make members non static
  .github/workflows/main.yml
  Dockerfile
  README.md
  nginx/default.conf
  projects/dsp-ui/README.md
  projects/dsp-ui/src/lib/core/app-init.service.spec.ts
  projects/dsp-ui/src/lib/core/app-init.service.ts
  projects/dsp-ui/src/lib/core/core.module.ts
  projects/dsp-ui/src/lib/core/index.ts
  src/app/action-playground/action-playground.component.spec.ts
  src/app/app-init.service.ts
  src/app/app.module.ts
  src/app/read/read.component.ts
  src/main.ts
Labels: bug

#119 Add Gravsearch Generation Service
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/operator-constants.ts
  projects/dsp-ui/src/lib/search/index.ts
  projects/dsp-ui/src/lib/search/services/advanced-search-params.service.spec.ts
  projects/dsp-ui/src/lib/search/services/advanced-search-params.service.ts
  projects/dsp-ui/src/lib/search/services/gravsearch-generation.service.spec.ts
  projects/dsp-ui/src/lib/search/services/gravsearch-generation.service.ts
  src/app/advanced-search-playground/advanced-search-playground.component.html
  src/app/advanced-search-playground/advanced-search-playground.component.ts
Labels: enhancement

#84 Session service migration
  .github/workflows/main.yml
  Dockerfile
  README.md
  nginx/default.conf
  projects/dsp-ui/README.md
  projects/dsp-ui/src/lib/core/app-init.service.spec.ts
  projects/dsp-ui/src/lib/core/app-init.service.ts
  projects/dsp-ui/src/lib/core/core.module.ts
  projects/dsp-ui/src/lib/core/index.ts
  projects/dsp-ui/src/lib/core/session.service.spec.ts
  projects/dsp-ui/src/lib/core/session.service.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.spec.ts
  src/app/action-playground/action-playground.component.ts
  src/app/app-init.service.ts
  src/app/app.module.ts
  src/app/read/read.component.ts
  src/main.ts
Labels: breaking, enhancement, refactor, testing

#121 Flaky E2E Tests
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.html
  src/app/advanced-search-playground/advanced-search-playground.component.html
  src/app/advanced-search-playground/advanced-search-playground.component.spec.ts
  src/app/advanced-search-playground/advanced-search-playground.component.ts
Labels: bug

#123 Hide link to geonames.org in edit mode
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
Labels: refactor

#109 Create new value for existing property
  projects/dsp-ui/src/lib/assets/style/_viewer-child.scss
  projects/dsp-ui/src/lib/assets/style/_viewer-parent.scss
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.html
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.scss
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.scss
  projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.scss
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement

#127 Update JS-Lib Dep
  Makefile
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: chore, dependencies

#122 Simple list of resources
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/viewer-playground/viewer-playground.component.html
  src/app/viewer-playground/viewer-playground.component.scss
  src/app/viewer-playground/viewer-playground.component.spec.ts
  src/app/viewer-playground/viewer-playground.component.ts
Labels: enhancement

#125 Login Form Migration
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.html
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.scss
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.spec.ts
  projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.spec.ts
Labels: enhancement

#132 Migrate Stringify String Literal Pipe
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
  src/app/app.component.scss
Labels: chore

#133 Update assets folder and file structrue
  angular.json
  package.json
  projects/dsp-ui/README.md
  projects/dsp-ui/src/assets/i18n/statusMsg.ts
  projects/dsp-ui/src/assets/style/_config.scss
  projects/dsp-ui/src/assets/style/_mixins.scss
  projects/dsp-ui/src/assets/style/_responsive.scss
  projects/dsp-ui/src/assets/style/_search.scss
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/action/components/message/message.component.scss
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.scss
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.scss
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.scss
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.scss
  projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.scss
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.scss
  src/styles.scss
Labels: chore

#128 Add Still Image Viewer
  angular.json
  package-lock.json
  package.json
  projects/dsp-ui/karma.conf.js
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.html
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.scss
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.spec.ts
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/still-image/still-image-playground.component.html
  src/app/still-image/still-image-playground.component.scss
  src/app/still-image/still-image-playground.component.spec.ts
  src/app/still-image/still-image-playground.component.ts
  yalc.lock
Labels: enhancement

#136 Build lib including assets folder
  package.json
  projects/dsp-ui/README.md
  projects/dsp-ui/ng-package.json
  src/styles.scss
Labels: enhancement

#131 Migrate String Literal Input Component
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.html
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.scss
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.spec.ts
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
Labels: chore

#138 Optimise the number of cards per line
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.scss
Labels: enhancement, styling

#140 Warning When Running Lib's Tests
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
Labels: bug, testing

#141 Change Home Icon of OpenSeadragon Viewer
  projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.html
Labels: styling

#142 FIX: DSP UI is blocked when submitting an invalid value
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
Labels: bug

#143 Prerelease of v1.0.0 rc.2
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/README.md
  projects/dsp-ui/package.json
Labels: chore

#144 Update CHANGELOG and READMEs
  CHANGELOG.md
  README.md
  projects/dsp-ui/README.md
Labels: documentation
