Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-06, with the labels that each got.

#91 Migrate action module directives
  package-lock.json
  package.json
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/directives/admin-image/admin-image.config.ts
  projects/dsp-ui/src/lib/action/directives/admin-image/admin-image.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/admin-image/admin-image.directive.ts
  projects/dsp-ui/src/lib/action/directives/existing-names/existing-name.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/existing-names/existing-name.directive.ts
  projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.ts
  projects/dsp-ui/src/lib/action/directives/jdn-datepicker/jdn-datepicker.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/jdn-datepicker/jdn-datepicker.directive.ts
Labels: chore

#93 Progress Indicator
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.html
  projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.scss
  projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.spec.ts
  projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  src/app/modify/modify.component.html
  src/app/modify/modify.component.ts
  src/app/read/read.component.html
  src/app/read/read.component.ts
Labels: chore

#94 Migrate sort button
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.html
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.scss
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.spec.ts
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.scss
  src/app/action-playground/action-playground.component.spec.ts
  src/app/action-playground/action-playground.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
Labels: chore

#97 FIX: Action Module Playground & Components Missing Imports
  projects/dsp-ui/ng-package.json
  projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.spec.ts
  src/app/action-playground/action-playground.component.spec.ts
Labels: bug

#99 Update README
  README.md
Labels: documentation

#95 Migration of message component
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.html
  projects/dsp-ui/src/lib/action/components/message/message.component.scss
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/action/components/message/message.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/assets/i18n/statusMsg.ts
  projects/dsp-ui/src/lib/assets/style/_responsive.scss
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.spec.ts
  src/app/action-playground/action-playground.component.ts
  src/app/modify/modify.component.spec.ts
Labels: chore

#101 Refactor Sort Button
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.spec.ts
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
Labels: refactor

#102 FIX: Sort button type annotation
  projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
Labels: bug

#100 Use strictTemplates Compiler Option
  .github/workflows/main.yml
  Makefile
  package.json
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/tsconfig.lib.json
  tsconfig.json
Labels: build, enhancement

#106 FIX: display-edit dev build errors
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
Labels: bug

#108 Replace @knora/api with @dasch-swiss/dsp-js
  .gitignore
  Makefile
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/README.md
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/ng-package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.ts
  projects/dsp-ui/src/lib/core/core.module.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/base-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/subList-value/sublist-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/action-playground/action-playground.component.ts
  src/app/app-init.service.ts
  src/app/modify/modify.component.spec.ts
  src/app/modify/modify.component.ts
  src/app/read/read.component.spec.ts
  src/app/read/read.component.ts
Labels: build

#110 Remove jdn-datepicker directive from action module directives
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/directives/jdn-datepicker/jdn-datepicker.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/jdn-datepicker/jdn-datepicker.directive.ts
  projects/dsp-ui/src/lib/action/index.ts
Labels: chore

#111 Make the sorting service more flexible
  projects/dsp-ui/src/lib/action/services/sorting.service.spec.ts
  projects/dsp-ui/src/lib/action/services/sorting.service.ts
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#112 Use latest rc of dsp-js and other improvements
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/LICENSE
  projects/dsp-ui/README.md
  projects/dsp-ui/package.json
Labels: enhancement

#113 Update JS-Lib Dep
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: chore

#105 Move the search-panel and the fulltext-search components
  package-lock.json
  projects/dsp-ui/src/lib/assets/style/_mixins.scss
  projects/dsp-ui/src/lib/assets/style/_search.scss
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.html
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.scss
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/search/index.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.scss
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.spec.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
  projects/dsp-ui/src/lib/search/search.module.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/search-playground/search-playground.component.html
  src/app/search-playground/search-playground.component.scss
  src/app/search-playground/search-playground.component.spec.ts
  src/app/search-playground/search-playground.component.ts
  src/app/search-playground/search-results/search-results.component.html
  src/app/search-playground/search-results/search-results.component.scss
  src/app/search-playground/search-results/search-results.component.spec.ts
  src/app/search-playground/search-results/search-results.component.ts
Labels: enhancement

#115 DSP-UI Live Reloading
  README.md
  package.json
Labels: enhancement
