Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-12, with the labels that each got.

#237 DSP-1110 Bug fixes and styling improvement in resource viewer
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/viewer-playground/viewer-playground.component.html
  src/app/viewer-playground/viewer-playground.component.scss
  src/app/viewer-playground/viewer-playground.component.ts
Labels: bug, refactor

#238 DSP-1132 Advanced search limit to project
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.spec.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
  src/app/search-playground/search-playground.component.html
Labels: enhancement

#242 Update dsp-js-lib
  package-lock.json
  package.json
  projects/dsp-ui/package.json
Labels: dependencies

#239 Use new methods for ontology info processing
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/select-property.component.html
  projects/dsp-ui/src/lib/search/advanced-search/select-property/select-property.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/select-property.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/specify-property-value.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-resource-class/select-resource-class.component.spec.ts
Labels: enhancement

#243 DSP-1168 Release please action instead release drafter
  .github/release-drafter.yml
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
Labels: chore

#245 DSP-1175 - Change Required Validator for Value Components to be Optional
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/src/lib/viewer/values/base-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
Labels: enhancement

#247 chore(CI): Update workflow
  .github/workflows/main.yml
Labels: chore

#248 Update js-lib version to v1.0.1
  package-lock.json
  package.json
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/operator-constants.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
Labels: dependencies

#249 chore: update dsp-js version
  projects/dsp-ui/package.json
Labels: chore
