Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-08, with the labels that each got.

#139 Create New Value V2
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.html
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.scss
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
  projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement

#137 Better data handling in search module components
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.scss
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.spec.ts
  projects/dsp-ui/src/lib/search/expert-search/expert-search.component.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.html
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
  projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.spec.ts
  projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  src/app/advanced-search-playground/advanced-search-playground.component.html
  src/app/advanced-search-playground/advanced-search-playground.component.ts
  src/app/search-playground/search-playground.component.html
  src/app/search-playground/search-playground.component.scss
  src/app/search-playground/search-playground.component.ts
Labels: breaking, enhancement, refactor

#146 Add missing regex variables
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/values/custom-regex.ts
Labels: enhancement

#149 Export operator.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/operator.ts
  projects/dsp-ui/src/lib/search/index.ts
Labels: enhancement

#145 Update process of release notes
  .github/workflows/main.yml
Labels: chore

#148 Prerelease 1.0.0-rc.3
  .grenrc
  CHANGELOG.md
  Makefile
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
Labels: chore

#151 Update dsp-js-lib to version 1.0.0-rc.6
  projects/dsp-ui/package.json
Labels: dependencies

#150 Action Module Confirmation Dialog Component
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#147 Delete property value
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss
  projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#152 List of properties: refactor and redesign
  projects/dsp-ui/src/assets/style/_responsive.scss
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/assets/style/dsp-ui.scss
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.scss
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
  src/app/viewer-playground/viewer-playground.component.html
  src/app/viewer-playground/viewer-playground.component.spec.ts
  src/app/viewer-playground/viewer-playground.component.ts
Labels: enhancement, styling

#156 FIX: hide the add button for an XML text property
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
Labels: chore

#153 Error handling: submitting duplicate values
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
Labels: enhancement

#155 Experimental: Alternative approach to resource/property view UI buttons
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  package.json
  projects/dsp-ui/src/assets/style/_viewer.scss
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
Labels: enhancement

#159 Make URI values clickable
  package-lock.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
Labels: enhancement

#160 Emit link value when clicked on
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
Labels: enhancement

#162 Export GND directive
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.spec.ts
  projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.ts
  src/app/action-playground/action-playground.component.html
Labels: bug

#164 dsp-property-toolbar warnings in unit tests
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
Labels: chore
