Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2020-05, with the labels that each got.

#67 Improve read mode appearance of value components
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.spec.ts
  projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.ts
  projects/knora-ui/src/lib/viewer/values/base-value.component.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
Labels: enhancement, styling

#70 Remove readonly inputs
  projects/knora-ui/src/lib/viewer/index.ts
  projects/knora-ui/src/lib/viewer/pipes/formatted-boolean.pipe.spec.ts
  projects/knora-ui/src/lib/viewer/pipes/formatted-boolean.pipe.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
  projects/knora-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-input/date-input.component.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/viewer.module.ts
Labels: chore

#71 cdkTextareaAutosize code cleanup
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.html
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
Labels: refactor

#77 FIX: KnoraDatePipe return values
  projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.spec.ts
  projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts
Labels: bug

#76 Use @knora/api 1.0.0-rc.0
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  projects/knora-ui/package.json
  projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
  projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
  projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  yalc.lock
Labels: chore

#79 Use Material Component Harness in Tests For Date
  projects/dsp-ui/src/lib/viewer/values/date-value/calendar-header/calendar-header.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
Labels: testing

#81 Add ngx-color-picker to lib's peer deps
  projects/dsp-ui/package.json
Labels: chore

#72 Step by step guidelines in the READMEs
  README.md
  package.json
  projects/dsp-ui/README.md
Labels: documentation

#83 Preparing Release Candidate v1.0.0-rc.0
  .editorconfig
  .github/workflows/main.yml
  .github/workflows/nodejs.yml
  .grenrc
  Makefile
Labels: enhancement

#85 Prerelease v1.0.0-rc.1
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
  projects/dsp-ui/README.md
  projects/dsp-ui/package.json
Labels: build

#73 Custom Boolean Pipe
  projects/dsp-ui/src/lib/viewer/pipes/formatted-boolean.pipe.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
Labels: enhancement

#86 Update package information
  CHANGELOG.md
  README.md
  projects/dsp-ui/package.json
Labels: chore

#87 Describe concept of value components
  projects/dsp-ui/README.md
  projects/dsp-ui/design-documentation.md
Labels: documentation

#82 Action module pipes migration
  projects/dsp-ui/design-documentation.md
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/action/pipes/array-transformation/reverse.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/array-transformation/reverse.pipe.ts
  projects/dsp-ui/src/lib/action/pipes/array-transformation/sort-by.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/array-transformation/sort-by.pipe.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/formatted-boolean.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/formatted-boolean.pipe.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.ts
  projects/dsp-ui/src/lib/action/services/sorting.service.spec.ts
  projects/dsp-ui/src/lib/action/services/sorting.service.ts
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/pipes/formatted-boolean.pipe.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/public-api.ts
  src/app/app.module.ts
Labels: breaking, chore

#88 Refactor how to get properties by type
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: enhancement

#89 Refactor Truncate Pipe
  projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.ts
Labels: refactor

#92 Update tslint
  tslint.json
Labels: chore

#90 Int Value Comp Specs: Using MatHarness
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
Labels: testing
