Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2021-05, with the labels that each got.

#291 chore(viewer): export value operation events (DSP-1590)
  projects/dsp-ui/src/lib/viewer/index.ts
Labels: chore

#290 feat(advanced search): try to reuse resource and property selection (DSP-1587)
  .github/workflows/main.yml
  e2e/src/app.e2e-spec.ts
  package.json
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.html
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.scss
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.html
  projects/dsp-ui/src/lib/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.scss
  projects/dsp-ui/src/lib/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.spec.ts
  projects/dsp-ui/src/lib/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts
  projects/dsp-ui/src/lib/search/advanced-search/select-resource-class/select-resource-class.component.scss
  projects/dsp-ui/src/lib/search/search.module.ts
Labels: enhancement

#294 feat(list-view): Create boolean flag to enable/disable the view switcher (DSP-1597)
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
Labels: enhancement

#296 chore(github actions): replace token
  .github/workflows/main.yml
Labels: chore

#295 docs(advanced search): update naming to advanced search (DSP-1651)
  README.md
  docs/assets/images/advanced-search-linked-resource.png
  docs/assets/images/advanced-search-match.png
  docs/assets/images/advanced-search-regex.png
  docs/assets/images/advanced-search.png
  docs/how-to-contribute/design-documentation.md
  docs/how-to-use/search/advanced-search-user-docs.md
  docs/how-to-use/search/advanced-search.md
  docs/how-to-use/search/expert-search.md
  docs/how-to-use/search/extended-search.md
  docs/how-to-use/search/index.md
  docs/how-to-use/search/search-panel.md
  docs/how-to-use/viewer/search-results.md
  mkdocs.yml
  projects/dsp-ui/src/lib/search/advanced-search/resource-and-property-selection/select-property/specify-property-value/operator-constants.ts
  projects/dsp-ui/src/lib/search/services/advanced-search-params.service.spec.ts
  projects/dsp-ui/src/lib/search/services/advanced-search-params.service.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
Labels: documentation, user requirement
