Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2021-07, with the labels that each got.

#311 feat(viewer): add checkbox for every resource in list and grid view (DSP-1711)
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.scss
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts
  src/app/search-playground/search-playground.component.html
  src/app/search-playground/search-playground.component.ts
Labels: enhancement

#313 feat(action): intermediate page for selected resources in comparison viewer (DSP-1765)
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.html
  projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.scss
  projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.spec.ts
  projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.ts
  projects/dsp-ui/src/lib/action/index.ts
  src/app/action-playground/action-playground.component.html
  src/app/action-playground/action-playground.component.ts
Labels: enhancement

#315 feat(viewer): recognise URLs in text value and convert into link (DSP-1595)
  projects/dsp-ui/src/lib/action/action.module.ts
  projects/dsp-ui/src/lib/action/index.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/linkify.pipe.spec.ts
  projects/dsp-ui/src/lib/action/pipes/string-transformation/linkify.pipe.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  src/app/modify/modify.component.ts
  src/app/read/read.component.ts
Labels: enhancement

#316 feat(viewer): split pane to compare multiple resource (DSP-1785)
  package.json
  projects/dsp-ui/src/lib/viewer/index.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
  projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.html
  projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.scss
  projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.ts
  src/app/viewer-playground/viewer-playground.component.html
  src/app/viewer-playground/viewer-playground.component.ts
Labels: enhancement

#319 refactor(resource): clean up code and refactoring (DSP-1816)
  package-lock.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.service.spec.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.service.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts
Labels: refactor

#322 chore(deps): bump dsp-js to latest version (DSP-1825)
  .github/workflows/main.yml
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/core/session.service.ts
  src/app/advanced-search-playground/advanced-search-playground.component.ts
  vars.mk
Labels: chore, dependencies

#324 fix(viewer): fix several issues in list-view (DSP-1575)
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
  projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
Labels: bug, enhancement
