Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2021-06, with the labels that each got.

#298 feat(date input): create new component for date input (DSP-94)
  projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
  projects/dsp-ui/src/lib/viewer/viewer.module.ts
Labels: enhancement, user requirement

#301 feat(viewer): improve style of date input (DSP-1724)
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.scss
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.scss
Labels: enhancement

#304 chore(gh-ci): update docs deployment (DSP-1741)
  .github/workflows/main.yml
Labels: bug, chore

#303 feat(viewer): make hex code display optional for color value (DSP-1667)
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts
Labels: user requirement

#305 feat(viewer): resolve geoname id and show name (DSP-1212)
  projects/dsp-ui/src/lib/viewer/services/geoname.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/geoname.service.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
  src/app/viewer-playground/viewer-playground.component.spec.ts
  src/config/config.dev.json
  src/config/config.prod.json
Labels: user requirement

#307 feat(viewer): improve editing of geonames (DSP-1212)
  projects/dsp-ui/src/lib/viewer/services/geoname.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/geoname.service.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
Labels: user requirement

#308 docs(improve docs): add some missing parts (DSP-1752)
  docs/how-to-contribute/design-documentation.md
  docs/how-to-use/getting-started.md
Labels: documentation

#299 chore(environment): add test-server config (DSP-1717)
  angular.json
  docs/how-to-contribute/index.md
  package.json
  src/config/config.test-server.json
  src/environments/environment.test-server.ts
Labels: chore
