Repository dasch-swiss/dsp-ui-lib, pull requests merged in 2021-01, with the labels that each got.

#250 Fix Value Form Control Name
  projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts
Labels: bug

#252 chore: update pr template (DSP-1189)
  .github/pull_request_template.md
Labels: chore

#251 fix(Date Value Validators): Propagate valueRequiredValidator to child component (DSP-1188)
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.ts
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
  projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
Labels: bug

#253 fix(Interval Value Validators): Propagate valueRequiredValidator to child component (DSP-1193)
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts
Labels: bug

#257 fix(Time Value Validators): Propagate valueRequiredValidator to child component (DSP-1218)
  projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
  projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts
Labels: bug

#258 chore: update JS-Lib version to 1.1.0
  package-lock.json
  package.json
Labels: chore

#255 chore: release 1.0.1
  projects/dsp-ui/CHANGELOG.md
  projects/dsp-ui/package.json
Labels: autorelease: pending

#259 chore: release 1.0.1
  .github/workflows/main.yml
Labels: autorelease: pending

#261 fix(Link Value): custom validator should allow null (DSP-1237)
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
Labels: bug

#263 refactor: update constants (DSP-1187)
  projects/dsp-ui/package.json
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
  projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
  projects/dsp-ui/src/lib/viewer/services/value.service.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
  projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
Labels: refactor

#264 feat(viewer): integrate file upload component in form logic (DSP-1257)
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.html
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.spec.ts
  projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.ts
  projects/dsp-ui/src/lib/viewer/services/upload-file.service.spec.ts
  src/app/upload-playground/upload-playground.component.html
  src/app/upload-playground/upload-playground.component.ts
Labels: enhancement

#267 test(e2e): improve stability of e2e tests.
  e2e/src/app.e2e-spec.ts
Labels: testing

#269 feat(string-literal-input): updates input on label changes (DSP-1295)
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.spec.ts
  projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.ts
Labels: enhancement

#270 chore: update dsp-js version to 1.2.1
  package-lock.json
  package.json
  projects/dsp-ui/package.json
  vars.mk
Labels: chore
